64 setup sdk package test
BIGmama-technology/Hyko-sdk pull request #68
Opened 2024-03-28 08:29 UTC by Louai-Zokerburg

#64

2024-03-31 13:16 UTC, 1hachem requested changes
- after you merge please update the tests for defintions (build instead of push ...)
- add a dockerfile where you run the test, all sample files should be inside docker container

2024-03-31 14:47 UTC, Louai-Zokerburg commented on Dockerfile
@1hachem Need assistance here to setup tests environment for tests, what really confused me is in of the tests tests/test_defenitions.py::test_build i need to read an actual Dockerfile and build it, how can i do so in the container?!

2024-03-31 16:46 UTC, 1hachem commented on Dockerfile
lets avoid running docker (subprocess) inside docker (test container) inside docker (github action docker)...

2024-03-31 16:47 UTC, 1hachem commented on Dockerfile
[checkout this](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/) maybe interesting for you

2024-04-02 21:17 UTC, strlrd-29 approved these changes

2024-04-02 21:17 UTC, merged